from __future__ import annotations
from typing import Protocol, List, Optional
from app.domain.models import Task

class TaskRepository(Protocol):
    def list(self) -> List[Task]: ...
    def get(self, task_id: int) -> Optional[Task]: ...
    def add(self, title: str) -> Task: ...
    def delete(self, task_id: int) -> Task: ...
    def set_done(self, task_id: int, done: bool) -> Task: ...
    def restore(self, task: Task) -> None: ...